### ISSUE TITLE
The mod CRASHES for unknown reason.

### ISSUE THREAD

**Issue by jLn0n** [kinderhead/LuaDatapack#10]
**Version**
0.9.0 beta

[crash-2023-06-01_00.05.49-client.txt](https://github.com/kinderhead/LuaDatapack/files/11624904/crash-2023-06-01_00.05.49-client.txt)

**Comment by kinderhead** [comment]
I never noticed it, but I also get that error. I'm looking into it now. In the meantime try using the latest version (0.10.0-beta) with pure fabric instead of quilt

**Comment by kinderhead** [comment]
Fixed with version 0.10.1-beta

**Comment by jLn0n** [comment]
> Fixed with version 0.10.1-beta. I see no reason why it would not work on Quilt now

thank u kind sir :D
