### ISSUE TITLE
use __tostring metamethod in tables when available on print

### ISSUE THREAD

**Issue by jLn0n** [kinderhead/LuaDatapack#11]
currently it parses the table with or without the __tostring metamethod ([look at dis](https://github.com/kinderhead/LuaDatapack/blob/master/src/main/java/mod/kinderhead/luadatapack/lua/api/LuastdLib.java#L174)) when printing, it would be great because the normal print function does use the __tostring method.

example code for table with __tostring metamethod:
```lua
local test = setmetatable({}, {__tostring = function() return "Hello World!" end})
print(test) -- prints "Hello World!" instead of {} which is empty table
```

i might prefer if the `print` function does act like i have explained above and not modifying/touching the `print_db` function

**Comment by kinderhead** [comment]
Should work when 0.10.2-beta releases. If you want the change earlier, then check the [github actions](https://github.com/kinderhead/LuaDatapack/actions/runs/5156133633#artifacts) for the latest commit to find a version to download

**Comment by jLn0n** [comment]
> Should work when 0.10.2-beta releases. If you want the change earlier, then check the [github actions](https://github.com/kinderhead/LuaDatapack/actions/runs/5156133633#artifacts) for the latest commit to find a version to download

thank you kind sir :D
