### ISSUE TITLE
[Question]: How to use

### ISSUE THREAD

**Issue by frinkifail** [kinderhead/LuaDatapack#15]
You should add more examples and documentation because I have literally no idea how to use this.

**Comment by kinderhead** [comment]
Well it's in beta, and also I haven't worked on it in a while (I will at some point). I will add more examples later. You should be able to look at the current documentation and get a decent idea on how it works.
[Here](https://kinderhead.github.io/LuaDatapack/modules/global.html) are some global functions that you can access anywhere
[Here](https://kinderhead.github.io/LuaDatapack/interfaces/commands.Commands.html) are some basic commands I've implemented so far. If you want to use one that is not in this list then use the `command()` function.

**Comment by frinkifail** [comment]
how do i use the modules

**Comment by kinderhead** [comment]
You can import modules by doing `local mod = require(module_name)`. A list of built in modules can be found [here](https://github.com/kinderhead/LuaDatapack#standard-library). If you want to import your own libraries then use `require` but with the same name you would use with `/lua`.
