### ISSUE TITLE
[Bug]: Freeze when `while true do`

### ISSUE THREAD

**Issue by frinkifail** [kinderhead/LuaDatapack#16]
**Version**
0.11.0-beta

**Problematic script or function**
```
while true do
    print("freeze")
end
```

**Error message or response**
Literally just freezes the server.

**Expected outcome**
Can't do `while true do`

**Work around**
None

**Comment by kinderhead** [comment]
That's because it wants to run the whole script on the same tick. You can accomplish this by making a script (`foo:tick` for example) and adding it to your `_project.lua` file. Check the README on how to do that. In the `foo:tick` file you put the `print("freeze")` line without the while loop.
